## **Exo 1**

In [ ]:
import numpy as np

class ArrayStats:
    def __init__(self, data):
        try:
            array = np.asarray(data)
        except Exception as e:
            raise TypeError("Conversion to numpy array failed") from e

        if array.size == 0:
            raise ValueError("Array cannot be empty")

        if array.ndim > 2:
            raise ValueError("Array dimension must be 1D or 2D only")

        self._array = array.copy()
        

    def shape(self) -> tuple:
        return self._array.shape

    def ndim(self) -> int:
        return self._array.ndim

    def dtype(self):
        return self._array.dtype

    def is_2d(self) -> bool:
        return self._array.ndim == 2

    def row_count(self) -> int:
        if self._array.ndim == 1:
            return self._array.shape[0]
        return self._array.shape[0]

    def column_count(self) -> int:
        if self._array.ndim == 1:
            return 1
        return self._array.shape[1]

# tests
ArrayStats([1,2,3])
try:
    ArrayStats([])
    assert False, "Expected ValueError"
except:
    pass
ArrayStats(np.array([[1,2,3]]))
ArrayStats("abc")

## **Exo 2**

In [28]:
import numpy as np

class MatrixAggregator:
    def __init__(self, data):
        try:
            matrix = np.asarray(data)
        except Exception as e:
            raise TypeError("Conversion to numpy array failed") from e

        if matrix.size == 0:
            raise ValueError("Matrix cannot be empty")

        if matrix.ndim != 2:
            raise ValueError("Matrix must be strictly 2D")

        self._matrix = matrix.copy()

    def _validate_axis(self, axis):
        if axis not in (None, 0, 1):
            raise ValueError("Axis must be None, 0 or 1")

    def sum(self, axis: int | None = None):
        self._validate_axis(axis)
        return self._matrix.sum(axis=axis)

    def mean(self, axis: int | None = None):
        self._validate_axis(axis)
        return self._matrix.mean(axis=axis)

    def max(self, axis: int | None = None):
        self._validate_axis(axis)
        return self._matrix.max(axis=axis)

    def argmax(self, axis: int | None = None):
        self._validate_axis(axis)
        return self._matrix.argmax(axis=axis)
        
# Tests
m = MatrixAggregator([[1,2,3],
                      [4,5,6]])

m.sum()
m.sum(axis=0)
m.sum(axis=1)

m.argmax(axis=0)
m.argmax(axis=1)

array([2, 2])

## **Exo 3**

In [44]:
import numpy as np

class FeatureScaler:
    def __init__(self, data):
        try:
            matrix = np.asarray(data)
        except Exception as e:
            raise TypeError("Conversion to numpy array failed") from e

        if matrix.size == 0:
            raise ValueError("Matrix cannot be empty")

        if matrix.ndim != 2:
            raise ValueError("Matrix must be strictly 2D")

        self._X = matrix.copy()

    def scale(self, mean, std):
        mean = np.asarray(mean)
        std = np.asarray(std)

        n_features = self._X.shape[1]

        # Validation dimension mean
        if mean.ndim > 1:
            raise ValueError("Mean must be scalar or 1D array")

        if mean.ndim == 1 and mean.shape[0] != n_features:
            raise ValueError("Mean length must match number of features")

        # Validation dimension std
        if std.ndim > 1:
            raise ValueError("Std must be scalar or 1D array")

        if std.ndim == 1 and std.shape[0] != n_features:
            raise ValueError("Std length must match number of features")

        # Interdiction division par zéro
        if np.any(std == 0):
            raise ValueError("Std cannot contain zero")

        return (self._X - mean) / std

# Tests
X1 = FeatureScaler([[1,2,3],[4,5,6]])
X1.scale(mean=0, std=1)
X1.scale(mean=[1,2,3], std=[1,1,1])

array([[0., 0., 0.],
       [3., 3., 3.]])

## **Exo 4**

In [55]:
import numpy as np

X = np.array([
    [1, 20, 3],
    [4, 50, 6],
    [7, 80, 9],
    [10, 5, 12]
])

# 1️Lignes où la 2ᵉ colonne > 30
mask_col2 = X[:, 1] > 30
result1 = X[mask_col2]


# 2️Lignes où au moins une valeur > 70
mask_any_70 = (X > 70).any(axis=1)
result2 = X[mask_any_70]


# Colonnes où la moyenne > 5
mask_mean = X.mean(axis=0) > 5
result3 = X[:, mask_mean]


# Remplacer toutes les valeurs < 5 par 0 (sans modifier X)
X_copy = X.copy()
X_copy[X_copy < 5] = 0
result4 = X_copy

## **Exo 5**

In [66]:
X = np.array([
    [1, 20, 3],
    [4, 50, 6],
    [7, 80, 9]
])

# I
X1 = np.where(X > 10, 1, 0)
# II
X2 = np.where(
    X < 5,
    -1,
    np.where(X > 50, 1, 0)
)
X2

array([[-1,  0, -1],
       [-1,  0,  0],
       [ 0,  1,  0]])

## **Exo 6**

In [69]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Produit élément par élément
elem = A * B

# Produit matriciel
matmul1 = A @ B
matmul2 = np.dot(A, B)
#print(matmul1)
print(elem)

[[ 5 12]
 [21 32]]


## **Exo 7**

In [71]:
X = np.array([10, 5, 20, 3])

# Tri (retourne tableau trié)
sorted_X = np.sort(X)

# Tri en place
X.sort()

# Argsort (retourne les indices du tri)
indices = np.argsort(X)

# Top 2 plus grandes valeurs
top2_idx = np.argsort(X)[-2:]
top2_values = X[top2_idx]

## **Exo 8**

In [72]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Concatenate vertical (empile lignes)
C1 = np.concatenate([A, B], axis=0)

# Concatenate horizontal (empile colonnes)
C2 = np.concatenate([A, B], axis=1)

# Raccourcis
V = np.vstack([A, B])
H = np.hstack([A, B])

## **Exo 9**

In [73]:
X = np.array([1, 2, 3])

Y = X          # même objet
Z = X[:]       # vue
W = X.copy()   # copie réelle

Y[0] = 100
print(X)  # modifié

Z[1] = 200
print(X)  # modifié

W[2] = 300
print(X)  # NON modifié

[100   2   3]
[100 200   3]
[100 200   3]


## **Exo 10**

In [74]:
import numpy as np

X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Reshape (nouvelle forme compatible)
X_reshaped = X.reshape(3, 2)

# Flatten → toujours une COPIE
X_flatten = X.flatten()

# Ravel → vue si possible (plus rapide)
X_ravel = X.ravel()
# Différence :
print(f" X_reshaped : {X_reshaped}")
print(f" X_flatten : {X_flatten}")
print(f"X_ravel : {X_ravel}")

 X_reshaped : [[1 2]
 [3 4]
 [5 6]]
 X_flatten : [1 2 3 4 5 6]
X_ravel : [1 2 3 4 5 6]
